package com.fitvisionai.fitvision_ai;

import android.Manifest; import android.app.*; import android.content.*; import android.content.pm.PackageManager; import android.location.*; import android.os.*; import androidx.core.app.NotificationCompat; import androidx.core.content.ContextCompat; import java.util.*; import io.flutter.plugin.common.EventChannel;

public final class RunningLocationService extends Service implements LocationListener {
  private static final String CHANNEL="fitvision_running"; private static final int ID=7407; private static volatile boolean running=false,paused=false; private static EventChannel.EventSink sink; private static RunningLocationService instance; private LocationManager manager; private long startedElapsed;
  static void setSink(EventChannel.EventSink value){sink=value;} static boolean isRunning(){return running;} static void setPaused(boolean value){paused=value;if(instance!=null)instance.notifyProgress(null,null);} static void updateProgress(Object duration,Object distance){if(instance!=null)instance.notifyProgress(duration,distance);}
  @Override public void onCreate(){super.onCreate();instance=this;manager=(LocationManager)getSystemService(LOCATION_SERVICE);createChannel();}
  @Override public int onStartCommand(Intent intent,int flags,int startId){if(running)return START_STICKY; running=true;paused=false;startedElapsed=SystemClock.elapsedRealtime();startForeground(ID,notification("Starting GPS…"));if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){stopSelf();return START_NOT_STICKY;}try{manager.requestLocationUpdates(LocationManager.GPS_PROVIDER,2000L,3f,this,Looper.getMainLooper());}catch(Exception ignored){stopSelf();}return START_STICKY;}
  @Override public void onLocationChanged(Location l){if(paused)return;EventChannel.EventSink current=sink;if(current==null)return;Map<String,Object> m=new HashMap<>();m.put("latitude",l.getLatitude());m.put("longitude",l.getLongitude());m.put("altitude",l.hasAltitude()?l.getAltitude():null);m.put("accuracy",(double)l.getAccuracy());m.put("verticalAccuracy",Build.VERSION.SDK_INT>=26&&l.hasVerticalAccuracy()?(double)l.getVerticalAccuracyMeters():null);m.put("speed",l.hasSpeed()?(double)l.getSpeed():null);m.put("speedAccuracy",Build.VERSION.SDK_INT>=26&&l.hasSpeedAccuracy()?(double)l.getSpeedAccuracyMetersPerSecond():null);m.put("bearing",l.hasBearing()?(double)l.getBearing():null);m.put("timestamp",l.getTime());m.put("elapsedRealtimeMs",l.getElapsedRealtimeNanos()/1000000L);current.success(m);}
  @Override public void onProviderDisabled(String provider){EventChannel.EventSink current=sink;if(current!=null)current.error("GPS_DISABLED","Location services are disabled",null);}
  private void createChannel(){NotificationManager nm=getSystemService(NotificationManager.class);nm.createNotificationChannel(new NotificationChannel(CHANNEL,"Active run tracking",NotificationManager.IMPORTANCE_LOW));}
  private Notification notification(String text){Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);return new NotificationCompat.Builder(this,CHANNEL).setSmallIcon(android.R.drawable.ic_menu_mylocation).setContentTitle(paused?"Run paused":"FitVision run in progress").setContentText(text).setOngoing(true).setOnlyAlertOnce(true).setContentIntent(pi).setCategory(NotificationCompat.CATEGORY_SERVICE).build();}
  private void notifyProgress(Object duration,Object distance){String d=duration==null?format(SystemClock.elapsedRealtime()-startedElapsed):duration.toString();String km=distance==null?"0.00":distance.toString();getSystemService(NotificationManager.class).notify(ID,notification(d+" • "+km+" km"));}
  private String format(long ms){long s=Math.max(0,ms/1000);return String.format(Locale.US,"%02d:%02d",s/60,s%60);}
  @Override public void onDestroy(){if(manager!=null)manager.removeUpdates(this);stopForeground(STOP_FOREGROUND_REMOVE);running=false;paused=false;instance=null;super.onDestroy();}
  @Override public android.os.IBinder onBind(Intent intent){return null;}
}
